plugins:
  - path: .yarn/plugins/@yarnpkg/plugin-typescript.cjs
    spec: "@yarnpkg/plugin-typescript"
  - path: .yarn/plugins/@yarnpkg/plugin-interactive-tools.cjs
    spec: "@yarnpkg/plugin-interactive-tools"

yarnPath: .yarn/releases/yarn-sources.cjs

packageExtensions:
  "@aws-amplify/api@*":
    dependencies:
      "@aws-amplify/auth": "*"
      "@aws-amplify/cache": "*"
      "@aws-amplify/core": "*"
  "@aws-amplify/datastore@*":
    dependencies:
      "@aws-amplify/auth": "*"
      "@aws-amplify/cache": "*"
      "crypto-js": "*"
  "@aws-amplify/storage@*":
    dependencies:
      "@aws-sdk/fetch-http-handler": "*"
      "@aws-sdk/protocol-http": "*"
      "@aws-sdk/querystring-builder": "*"
      "@aws-sdk/url-parser-node": "*"
  "@aws-amplify/ui-react@*":
    dependencies:
      "@aws-amplify/auth": "*"
      "@aws-amplify/core": "*"
